name: Cypress Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      # نصب مرورگر Chrome برای اجرای headless واقعی
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run Cypress tests
        run: npx cypress run --browser chrome --headless

      # آپلود artifactها برای بررسی نتایج در GitHub
      - name: Upload screenshots and videos
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
